[project]
name = "server-mindtube"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pymongo",
    "pyjwt",
    "passlib[bcrypt]",
    "bcrypt==4.0.1",
    "pydantic",
    "pydantic-settings",
    "email-validator",
    "python-dotenv",
    "google-auth>=2.55.0",
    "requests>=2.34.2",
    "httpx>=0.28.1",
]
